### ISSUE TITLE
Create Dinner Recipe

### ISSUE THREAD

**Issue by dagrove44** [IntroToCode/CodeMates6_Fall22#10]
## 💬 Discussion topic

We need a good dinner recipe for our dinner party

## ❗ Potential issues

No one here is a chef so we'll have to crowdsource to get to a good space

## 👥 People to consult

Let's consult the full team and see where we can get

## 📃 Details

Codemates 6!

**Comment by tj-considine** [comment]
Looks good to me!

**Comment by IanLBerkeleyHaas** [comment]
Lots of good input from the team, I think we have a great recipe for our dinner party
