### ISSUE TITLE
Create Breakfast Recipe

### ISSUE THREAD

**Issue by dagrove44** [IntroToCode/CodeMates6_Fall22#3]
## 💬 Discussion topic

We need to create a great breakfast recipe we all can enjoy!

## ❗ Potential issues

Lack of knowledge. Need to adjust the recipe and ingredient requirements. 

## 👥 People to consult

Teammates to crowdsource recipe ideas. 

## 📃 Details

We will need to adjust the recipe as a team until we have something that we all can agree will be tasty

**Comment by malrayes** [comment]
I agree we have to edit the recipe until we're sure that it makes the best banana pancakes ever

**Comment by Plzheng** [comment]
Hi @dagrove44, I have a different opinion on the servings on your edit. Our recipe should be able to serve 6 ppl instead of 2ppl, as we're targeting for big families!

**Comment by IanLBerkeleyHaas** [comment]
This recipe looks great, we should have enough pancakes to feed the whole family!
